import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
				if (localStorage.colorMode === 'dark' || (!('colorMode' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
				  document.documentElement.classList.add('dark')
				} else {
				  document.documentElement.classList.remove('dark')
				}
				
				// Whenever the user explicitly chooses light mode
				localStorage.colorMode = 'light'
				
				// Whenever the user explicitly chooses dark mode
				localStorage.colorMode = 'dark'
				
				// Whenever the user explicitly chooses to respect the OS preference
				localStorage.removeItem('colorMode')
			`,
          }}
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
